version: '3.7'
services:
  rest-api:
    container_name: rest-api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    build: # custom image oldugu icin. Dockerfile build edilecek.
        context: ./ 
    ports:
      - 3000:1337
  
  mongodb:
    image: mongodb
    ports:
      - 27017:27017
    volumes:
      - restapi-data:/data/db
  caddy:
    image: caddy/caddy:2.2.1-alpine
    container_name: caddy-service
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
    - $PWD/Caddyfile:/etc/caddy/Caddyfile
    - $PWD/site:/srv
    - caddy_data:/data
    - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
  restapi-data: